services:
  openmeteo:
    container_name: openmeteo_job
    build: .
    image: previsao-open-meteo:latest

    env_file:
      - .env

    volumes:
      - ./state:/app/state
      - ./data:/app/data

    restart: "no"
